spring:
  application:
    name: hello-dubbo-service-user-provider
user:
  service:
    version: 1.0.0
dubbo:
  scan:
    basePackages: com.mu.hellodubboserviceuserprovider
  application:
    id: hello-dubbo-service-user-provider
    name: hello-dubbo-service-user-provider
    qos-port: 22222
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    status: server
  registry:
    id: zookeeper
    address: zookeeper://192.168.0.126:2181?backup=192.168.0.126:2182,192.168.0.126:2183
